// Code generated by go-adtgen. DO NOT EDIT.
//go:build !adtgen_generate

package sum

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
)

type HogeOrFuga interface {
	isHogeOrFuga()
	AsHoge() (Hoge, bool)
	AsFuga() (Fuga, bool)
	GetID() string
	SetID(string)
}

func (*Hoge) isHogeOrFuga() {}

func (x *Hoge) AsHoge() (Hoge, bool) {
	if x == nil {
		var zero Hoge
		return zero, false
	}
	return *x, true
}

func (x *Hoge) AsFuga() (Fuga, bool) {
	if x == nil {
		var zero Fuga
		return zero, false
	}
	var zero Fuga
	return zero, false
}

func (x *Hoge) GetID() string {
	return x.Common.ID
}

func (x *Hoge) SetID(v string) {
	x.Common.ID = v
}

func (*Fuga) isHogeOrFuga() {}

func (x *Fuga) AsHoge() (Hoge, bool) {
	if x == nil {
		var zero Hoge
		return zero, false
	}
	var zero Hoge
	return zero, false
}

func (x *Fuga) AsFuga() (Fuga, bool) {
	if x == nil {
		var zero Fuga
		return zero, false
	}
	return *x, true
}

func (x *Fuga) GetID() string {
	return x.Common.ID
}

func (x *Fuga) SetID(v string) {
	x.Common.ID = v
}

func MatchHogeOrFuga[T any](v HogeOrFuga, whenHoge func(Hoge) T, whenFuga func(Fuga) T) T {
	switch x := v.(type) {
	case *Hoge:
		return whenHoge(*x)
	case *Fuga:
		return whenFuga(*x)
	default:
		panic("unreachable generated match for HogeOrFuga")
	}
}

func MatchHogeOrFuga2[S, T any](v HogeOrFuga, whenHoge func(Hoge) (S, T), whenFuga func(Fuga) (S, T)) (S, T) {
	switch x := v.(type) {
	case *Hoge:
		return whenHoge(*x)
	case *Fuga:
		return whenFuga(*x)
	default:
		panic("unreachable generated match for HogeOrFuga")
	}
}

func UnmarshalHogeOrFuga(data []byte) (HogeOrFuga, error) {
	var result HogeOrFuga
	matches := 0
	{
		var candidate Hoge
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&candidate); err == nil {
			var trailing struct{}
			if err := decoder.Decode(&trailing); err == io.EOF {
				matches++
				result = &candidate
			}
		}
	}
	{
		var candidate Fuga
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&candidate); err == nil {
			var trailing struct{}
			if err := decoder.Decode(&trailing); err == io.EOF {
				matches++
				result = &candidate
			}
		}
	}
	if matches == 1 {
		return result, nil
	}
	if matches == 0 {
		return nil, fmt.Errorf("no variants of HogeOrFuga matched JSON")
	}
	return nil, fmt.Errorf("multiple variants of HogeOrFuga matched JSON")
}
