// Code generated by go-adtgen. DO NOT EDIT.
//go:build !adtgen_generate

package multi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
)

type Alpha interface {
	isAlpha()
	AsLeft() (Left, bool)
	AsRight() (Right, bool)
}

func (*Left) isAlpha() {}

func (x *Left) AsLeft() (Left, bool) {
	if x == nil {
		var zero Left
		return zero, false
	}
	return *x, true
}

func (x *Left) AsRight() (Right, bool) {
	if x == nil {
		var zero Right
		return zero, false
	}
	var zero Right
	return zero, false
}

func (*Right) isAlpha() {}

func (x *Right) AsLeft() (Left, bool) {
	if x == nil {
		var zero Left
		return zero, false
	}
	var zero Left
	return zero, false
}

func (x *Right) AsRight() (Right, bool) {
	if x == nil {
		var zero Right
		return zero, false
	}
	return *x, true
}

func MatchAlpha[R any](v Alpha, whenLeft func(Left) R, whenRight func(Right) R) R {
	switch x := v.(type) {
	case *Left:
		return whenLeft(*x)
	case *Right:
		return whenRight(*x)
	default:
		panic("unreachable generated match for Alpha")
	}
}

func MatchAlpha2[R1, R2 any](v Alpha, whenLeft func(Left) (R1, R2), whenRight func(Right) (R1, R2)) (R1, R2) {
	switch x := v.(type) {
	case *Left:
		return whenLeft(*x)
	case *Right:
		return whenRight(*x)
	default:
		panic("unreachable generated match for Alpha")
	}
}

func UnmarshalAlpha(data []byte) (Alpha, error) {
	var result Alpha
	matches := 0
	{
		var candidate Left
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&candidate); err == nil {
			var trailing struct{}
			if err := decoder.Decode(&trailing); err == io.EOF {
				matches++
				result = &candidate
			}
		}
	}
	{
		var candidate Right
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&candidate); err == nil {
			var trailing struct{}
			if err := decoder.Decode(&trailing); err == io.EOF {
				matches++
				result = &candidate
			}
		}
	}
	if matches == 1 {
		return result, nil
	}
	if matches == 0 {
		return nil, fmt.Errorf("no variants of Alpha matched JSON")
	}
	return nil, fmt.Errorf("multiple variants of Alpha matched JSON")
}
