// Code generated by go-adtgen. DO NOT EDIT.
//go:build !adtgen_generate

package multi

import (
	"encoding/json"
	"fmt"
)

type Gamma interface {
	isGamma()
}

func (*Left) isGamma() {}

func (*Primary) isGamma() {}

func AsGammaLeft(v Gamma) (Left, bool) {
	if x, ok := v.(*Left); ok && x != nil {
		return *x, true
	}
	var zero Left
	return zero, false
}

func AsGammaPrimary(v Gamma) (Primary, bool) {
	if x, ok := v.(*Primary); ok && x != nil {
		return *x, true
	}
	var zero Primary
	return zero, false
}

func MatchGamma[R any](v Gamma, whenLeft func(Left) R, whenPrimary func(Primary) R) R {
	switch x := v.(type) {
	case *Left:
		if x != nil {
			return whenLeft(*x)
		}
		var zero Left
		return whenLeft(zero)
	case *Primary:
		if x != nil {
			return whenPrimary(*x)
		}
		var zero Primary
		return whenPrimary(zero)
	default:
		panic(fmt.Sprintf("unreachable generated match for %T", v))
	}
}

func MatchGamma2[R1, R2 any](v Gamma, whenLeft func(Left) (R1, R2), whenPrimary func(Primary) (R1, R2)) (R1, R2) {
	switch x := v.(type) {
	case *Left:
		if x != nil {
			return whenLeft(*x)
		}
		var zero Left
		return whenLeft(zero)
	case *Primary:
		if x != nil {
			return whenPrimary(*x)
		}
		var zero Primary
		return whenPrimary(zero)
	default:
		panic(fmt.Sprintf("unreachable generated match for %T", v))
	}
}

type GammaCases[R any] struct {
	Left    func(Left) R
	Primary func(Primary) R
	Default func(Gamma) R
}

func MatchGammaCases[R any](v Gamma, cases GammaCases[R]) R {
	switch x := v.(type) {
	case *Left:
		if cases.Left != nil {
			if x != nil {
				return cases.Left(*x)
			}
			var zero Left
			return cases.Left(zero)
		}
	case *Primary:
		if cases.Primary != nil {
			if x != nil {
				return cases.Primary(*x)
			}
			var zero Primary
			return cases.Primary(zero)
		}
	}
	if cases.Default != nil {
		return cases.Default(v)
	}
	panic(fmt.Sprintf("unhandled %T variant for Gamma", v))
}

type GammaCases2[R1, R2 any] struct {
	Left    func(Left) (R1, R2)
	Primary func(Primary) (R1, R2)
	Default func(Gamma) (R1, R2)
}

func MatchGammaCases2[R1, R2 any](v Gamma, cases GammaCases2[R1, R2]) (R1, R2) {
	switch x := v.(type) {
	case *Left:
		if cases.Left != nil {
			if x != nil {
				return cases.Left(*x)
			}
			var zero Left
			return cases.Left(zero)
		}
	case *Primary:
		if cases.Primary != nil {
			if x != nil {
				return cases.Primary(*x)
			}
			var zero Primary
			return cases.Primary(zero)
		}
	}
	if cases.Default != nil {
		return cases.Default(v)
	}
	panic(fmt.Sprintf("unhandled %T variant for Gamma", v))
}

func VisitGamma(v Gamma, whenLeft func(Left), whenPrimary func(Primary)) {
	switch x := v.(type) {
	case *Left:
		if x != nil {
			whenLeft(*x)
		} else {
			var zero Left
			whenLeft(zero)
		}
	case *Primary:
		if x != nil {
			whenPrimary(*x)
		} else {
			var zero Primary
			whenPrimary(zero)
		}
	default:
		panic(fmt.Sprintf("unreachable generated visit for %T", v))
	}
}

func MarshalGamma(v Gamma) ([]byte, error) {
	if v == nil {
		return []byte("null"), nil
	}
	switch x := v.(type) {
	case *Left:
		if x == nil {
			return []byte("null"), nil
		}
		return marshalWithGammaDiscriminator("event_type", "Left", *x)
	case *Primary:
		if x == nil {
			return []byte("null"), nil
		}
		return marshalWithGammaDiscriminator("event_type", "Primary", *x)
	default:
		return nil, fmt.Errorf("unknown Gamma variant %T", v)
	}
}

func marshalWithGammaDiscriminator(key, typeName string, v any) ([]byte, error) {
	data, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	if obj == nil {
		obj = make(map[string]json.RawMessage)
	}
	typeJSON, err := json.Marshal(typeName)
	if err != nil {
		return nil, err
	}
	obj[key] = typeJSON
	return json.Marshal(obj)
}

func UnmarshalGamma(data []byte) (Gamma, error) {
	var header struct {
		Type string `json:"event_type"`
	}
	if err := json.Unmarshal(data, &header); err != nil {
		return nil, err
	}
	switch header.Type {
	case "Left":
		var target Left
		if err := json.Unmarshal(data, &target); err != nil {
			return nil, err
		}
		return &target, nil
	case "Primary":
		var target Primary
		if err := json.Unmarshal(data, &target); err != nil {
			return nil, err
		}
		return &target, nil
	default:
		return nil, fmt.Errorf("unknown discriminator %q for Gamma", header.Type)
	}
}
