// Code generated by go-adtgen. DO NOT EDIT.
//go:build !adtgen_generate

package multi

type Beta struct {
	ID      string
	Enabled bool
}

func NewBeta(primary Primary, secondary Secondary) Beta {
	return Beta{
		ID:      primary.ID,
		Enabled: secondary.Enabled,
	}
}

func (x Beta) ToPrimary() Primary {
	return Primary{
		ID: x.ID,
	}
}

func (x Beta) ToSecondary() Secondary {
	return Secondary{
		Enabled: x.Enabled,
	}
}
