package emitter

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"maps"
	"slices"
	"strconv"
	"strings"

	"github.com/walnuts1018/go-adtgen/internal/model"
)

func Render(pkgName string, generated []model.GeneratedType) (string, error) {
	return RenderForPackage("", pkgName, generated)
}

func RenderForPackage(pkgPath string, pkgName string, generated []model.GeneratedType) (string, error) {
	return RenderFile(model.GeneratedFile{
		PackagePath: pkgPath,
		PackageName: pkgName,
		Generated:   generated,
	})
}

func RenderFile(file model.GeneratedFile) (string, error) {
	var buf bytes.Buffer
	buf.Grow(4096)

	buf.WriteString("// Code generated by go-adtgen. DO NOT EDIT.\n")
	buf.WriteString("//go:build !adtgen_generate\n\n")
	buf.WriteString("package " + file.PackageName + "\n\n")

	imports := mergeImports(file.Imports, collectImports(file.PackagePath, file.Generated))
	if len(imports) > 0 {
		writeImports(&buf, imports)
		buf.WriteString("\n")
	}

	qualifier := func(typePkg *types.Package) string {
		if typePkg == nil {
			return ""
		}
		if file.PackagePath != "" && typePkg.Path() == file.PackagePath {
			return ""
		}
		if name, ok := importNameForPath(imports, typePkg.Path()); ok && name != "" && name != "." && name != "_" {
			return name
		}
		return typePkg.Name()
	}

	for _, decl := range file.PassthroughDecls {
		buf.WriteString(decl)
		buf.WriteString("\n\n")
	}

	for i, generatedType := range file.Generated {
		if i > 0 {
			buf.WriteString("\n")
		}

		if generatedType.Kind == model.DeclarationKindSum && generatedType.Sum != nil {
			renderSumType(&buf, generatedType, qualifier)
			continue
		}

		renderProductType(&buf, generatedType, qualifier)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return "", err
	}

	return string(formatted), nil
}

func mergeImports(passthrough []model.PassthroughImport, generated []string) []model.PassthroughImport {
	merged := make([]model.PassthroughImport, 0, len(passthrough)+len(generated))
	for _, imp := range passthrough {
		if !containsImport(merged, imp.Name, imp.Path) {
			merged = append(merged, imp)
		}
	}
	for _, path := range generated {
		if hasImportPath(merged, path) {
			continue
		}
		merged = append(merged, model.PassthroughImport{Path: path})
	}

	slices.SortFunc(merged, func(a, b model.PassthroughImport) int {
		if cmp := strings.Compare(a.Path, b.Path); cmp != 0 {
			return cmp
		}
		return strings.Compare(a.Name, b.Name)
	})
	return merged
}

func containsImport(imports []model.PassthroughImport, name, path string) bool {
	for _, imp := range imports {
		if imp.Name == name && imp.Path == path {
			return true
		}
	}
	return false
}

func hasImportPath(imports []model.PassthroughImport, path string) bool {
	for _, imp := range imports {
		if imp.Path == path {
			return true
		}
	}
	return false
}

func importNameForPath(imports []model.PassthroughImport, path string) (string, bool) {
	for _, imp := range imports {
		if imp.Path == path {
			return imp.Name, true
		}
	}
	return "", false
}

func writeImports(buf *bytes.Buffer, imports []model.PassthroughImport) {
	if len(imports) == 1 && imports[0].Name == "" {
		buf.WriteString("import ")
		buf.WriteString(strconv.Quote(imports[0].Path))
		buf.WriteString("\n")
		return
	}

	buf.WriteString("import (\n")
	for _, imp := range imports {
		buf.WriteString("\t")
		if imp.Name != "" {
			buf.WriteString(imp.Name)
			buf.WriteString(" ")
		}
		buf.WriteString(strconv.Quote(imp.Path))
		buf.WriteString("\n")
	}
	buf.WriteString(")\n")
}

func collectImports(pkgName string, generated []model.GeneratedType) []string {
	seen := make(map[string]struct{})

	for _, generatedType := range generated {
		if generatedType.Kind == model.DeclarationKindSum && generatedType.Sum != nil {
			seen["encoding/json"] = struct{}{}
			seen["fmt"] = struct{}{}
			if generatedType.Sum.Discriminator == "" {
				seen["bytes"] = struct{}{}
				seen["io"] = struct{}{}
			}
			for _, method := range generatedType.Sum.InterfaceMethods {
				collectTypeImports(pkgName, method.Signature, seen)
			}
			for _, variant := range generatedType.Sum.Variants {
				collectTypeImports(pkgName, variant.Type, seen)
			}
			for _, field := range generatedType.Sum.CommonFields {
				collectTypeImports(pkgName, field.Type, seen)
			}
			continue
		}
		for _, input := range generatedType.Inputs {
			collectTypeImports(pkgName, input.Type, seen)
		}
		for _, field := range generatedType.Fields {
			collectTypeImports(pkgName, field.Type, seen)
		}
	}

	return slices.Sorted(maps.Keys(seen))
}

func collectTypeImports(pkgPath string, typ types.Type, seen map[string]struct{}) {
	if typ == nil {
		return
	}

	switch t := typ.(type) {
	case *types.Basic:
		return
	case *types.Pointer:
		collectTypeImports(pkgPath, t.Elem(), seen)
	case *types.Slice:
		collectTypeImports(pkgPath, t.Elem(), seen)
	case *types.Array:
		collectTypeImports(pkgPath, t.Elem(), seen)
	case *types.Map:
		collectTypeImports(pkgPath, t.Key(), seen)
		collectTypeImports(pkgPath, t.Elem(), seen)
	case *types.Chan:
		collectTypeImports(pkgPath, t.Elem(), seen)
	case *types.Signature:
		if recv := t.Recv(); recv != nil {
			collectTypeImports(pkgPath, recv.Type(), seen)
		}
		collectTupleImports(pkgPath, t.Params(), seen)
		collectTupleImports(pkgPath, t.Results(), seen)
	case *types.Struct:
		for field := range t.Fields() {
			collectTypeImports(pkgPath, field.Type(), seen)
		}
	case *types.Interface:
		for etyp := range t.EmbeddedTypes() {
			collectTypeImports(pkgPath, etyp, seen)
		}
	case *types.Named:
		if obj := t.Obj(); obj != nil && obj.Pkg() != nil && obj.Pkg().Path() != pkgPath {
			seen[obj.Pkg().Path()] = struct{}{}
		}
		if args := t.TypeArgs(); args != nil {
			for t := range args.Types() {
				collectTypeImports(pkgPath, t, seen)
			}
		}
	case *types.Alias:
		if obj := t.Obj(); obj != nil && obj.Pkg() != nil && obj.Pkg().Path() != pkgPath {
			seen[obj.Pkg().Path()] = struct{}{}
		}
		collectTypeImports(pkgPath, types.Unalias(t), seen)
	case *types.TypeParam:
		return
	case *types.Union:
		for term := range t.Terms() {
			collectTypeImports(pkgPath, term.Type(), seen)
		}
	case *types.Tuple:
		collectTupleImports(pkgPath, t, seen)
	}
}

func collectTupleImports(pkgPath string, tuple *types.Tuple, seen map[string]struct{}) {
	if tuple == nil {
		return
	}
	for v := range tuple.Variables() {
		collectTypeImports(pkgPath, v.Type(), seen)
	}
}

func renderProductType(buf *bytes.Buffer, generatedType model.GeneratedType, qualifier types.Qualifier) {
	buf.WriteString("type ")
	buf.WriteString(generatedType.Name)
	if len(generatedType.TypeParameters) > 0 {
		buf.WriteString("[")
		buf.WriteString(strings.Join(generatedType.TypeParameters, ", "))
		buf.WriteString("]")
	}
	buf.WriteString(" struct {\n")

	for _, field := range generatedType.Fields {
		buf.WriteString("\t")
		if !field.Anonymous {
			buf.WriteString(field.Name)
			buf.WriteString(" ")
		}
		buf.WriteString(types.TypeString(field.Type, qualifier))
		if field.Tag != "" {
			buf.WriteString(" `")
			buf.WriteString(field.Tag)
			buf.WriteString("`")
		}
		buf.WriteString("\n")
	}

	buf.WriteString("}\n")

	if len(generatedType.Inputs) == 0 {
		return
	}

	buf.WriteString("\n\n")
	renderConstructor(buf, generatedType, qualifier)

	for _, input := range generatedType.Inputs {
		buf.WriteString("\n\n")
		renderSplitMethod(buf, generatedType, input, qualifier)
	}
}

func renderSumType(buf *bytes.Buffer, generatedType model.GeneratedType, qualifier types.Qualifier) {
	buf.WriteString("type ")
	writeGeneratedTypeName(buf, generatedType, true)
	buf.WriteString(" interface {\n")
	buf.WriteString("\tis")
	buf.WriteString(generatedType.Name)
	buf.WriteString("()\n")
	for _, method := range generatedType.Sum.InterfaceMethods {
		buf.WriteString("\t")
		buf.WriteString(method.Name)
		buf.WriteString(renderInterfaceMethodSignature(method.Signature, qualifier))
		buf.WriteString("\n")
	}
	for _, field := range generatedType.Sum.CommonFields {
		buf.WriteString("\t")
		buf.WriteString(field.GetterName)
		buf.WriteString("() ")
		buf.WriteString(types.TypeString(field.Type, qualifier))
		buf.WriteString("\n")
		if generatedType.Sum.GenerateSetters {
			buf.WriteString("\t")
			buf.WriteString(field.SetterName)
			buf.WriteString("(")
			buf.WriteString(types.TypeString(field.Type, qualifier))
			buf.WriteString(")\n")
		}
	}
	buf.WriteString("}\n\n")

	for _, variant := range generatedType.Sum.Variants {
		renderSumVariantMethods(buf, generatedType, variant, qualifier)
		buf.WriteString("\n")
	}

	renderSumAsFunctions(buf, generatedType, qualifier)
	buf.WriteString("\n")
	renderSumMatchFunctions(buf, generatedType, qualifier)
	buf.WriteString("\n")

	if generatedType.Sum.Discriminator != "" {
		renderSumDiscriminatorMarshalUnmarshalFunctions(buf, generatedType, qualifier)
	} else {
		renderSumUnmarshalFunction(buf, generatedType, qualifier)
	}
}

func renderInterfaceMethodSignature(signature *types.Signature, qualifier types.Qualifier) string {
	if signature == nil {
		return "()"
	}

	rendered := types.TypeString(signature, qualifier)
	return strings.TrimPrefix(rendered, "func")
}

func renderSumVariantMethods(buf *bytes.Buffer, generatedType model.GeneratedType, variant model.GeneratedSumVariant, qualifier types.Qualifier) {
	valueType := types.TypeString(variant.Type, qualifier)
	pointerType := "*" + valueType

	buf.WriteString("func (")
	buf.WriteString(pointerType)
	buf.WriteString(") is")
	buf.WriteString(generatedType.Name)
	buf.WriteString("() {}\n\n")

	index := variantIndex(generatedType.Sum.Variants, variant.TypeName)
	for _, field := range generatedType.Sum.CommonFields {
		path := selectorPath("x", field.Paths[index])

		buf.WriteString("func (x ")
		buf.WriteString(pointerType)
		buf.WriteString(") ")
		buf.WriteString(field.GetterName)
		buf.WriteString("() ")
		buf.WriteString(types.TypeString(field.Type, qualifier))
		buf.WriteString(" {\n\treturn ")
		buf.WriteString(path)
		buf.WriteString("\n}\n\n")

		if generatedType.Sum.GenerateSetters {
			buf.WriteString("func (x ")
			buf.WriteString(pointerType)
			buf.WriteString(") ")
			buf.WriteString(field.SetterName)
			buf.WriteString("(v ")
			buf.WriteString(types.TypeString(field.Type, qualifier))
			buf.WriteString(") {\n\t")
			buf.WriteString(path)
			buf.WriteString(" = v\n}\n\n")
		}
	}
}

func renderSumAsFunctions(buf *bytes.Buffer, generatedType model.GeneratedType, qualifier types.Qualifier) {
	for _, variant := range generatedType.Sum.Variants {
		typeString := types.TypeString(variant.Type, qualifier)
		buf.WriteString("func As")
		buf.WriteString(generatedType.Name)
		buf.WriteString(variant.TypeName)
		writeFunctionTypeParameters(buf, generatedType.TypeParameters, nil)
		buf.WriteString("(v ")
		writeGeneratedTypeName(buf, generatedType, false)
		buf.WriteString(") (")
		buf.WriteString(typeString)
		buf.WriteString(", bool) {\n")
		buf.WriteString("\tif x, ok := v.(*")
		buf.WriteString(typeString)
		buf.WriteString("); ok && x != nil {\n\t\treturn *x, true\n\t}\n")
		buf.WriteString("\tvar zero ")
		buf.WriteString(typeString)
		buf.WriteString("\n\treturn zero, false\n}\n\n")
	}
}

func renderSumMatchFunctions(buf *bytes.Buffer, generatedType model.GeneratedType, qualifier types.Qualifier) {
	matchReturnType := uniqueTypeParameterNames(generatedType.TypeParameters, "R")

	// 1. Match<Sum>[R any]
	buf.WriteString("func Match")
	buf.WriteString(generatedType.Name)
	writeFunctionTypeParameters(buf, generatedType.TypeParameters, matchReturnType)
	buf.WriteString("(v ")
	writeGeneratedTypeName(buf, generatedType, false)
	buf.WriteString(", ")
	for i, variant := range generatedType.Sum.Variants {
		if i > 0 {
			buf.WriteString(", ")
		}
		buf.WriteString("when")
		buf.WriteString(variant.TypeName)
		buf.WriteString(" func(")
		buf.WriteString(types.TypeString(variant.Type, qualifier))
		buf.WriteString(") ")
		buf.WriteString(matchReturnType[0])
	}
	buf.WriteString(") ")
	buf.WriteString(matchReturnType[0])
	buf.WriteString(" {\n\tswitch x := v.(type) {\n")
	for _, variant := range generatedType.Sum.Variants {
		typeString := types.TypeString(variant.Type, qualifier)
		buf.WriteString("\tcase *")
		buf.WriteString(typeString)
		buf.WriteString(":\n\t\tif x != nil {\n\t\t\treturn when")
		buf.WriteString(variant.TypeName)
		buf.WriteString("(*x)\n\t\t}\n\t\tvar zero ")
		buf.WriteString(typeString)
		buf.WriteString("\n\t\treturn when")
		buf.WriteString(variant.TypeName)
		buf.WriteString("(zero)\n")
	}
	buf.WriteString("\tdefault:\n\t\tpanic(fmt.Sprintf(\"unreachable generated match for %T\", v))\n\t}\n}\n\n")

	// 2. Match<Sum>2[R1, R2 any]
	match2ReturnTypes := uniqueTypeParameterNames(generatedType.TypeParameters, "R1", "R2")
	buf.WriteString("func Match")
	buf.WriteString(generatedType.Name)
	buf.WriteString("2")
	writeFunctionTypeParameters(buf, generatedType.TypeParameters, match2ReturnTypes)
	buf.WriteString("(v ")
	writeGeneratedTypeName(buf, generatedType, false)
	buf.WriteString(", ")
	for i, variant := range generatedType.Sum.Variants {
		if i > 0 {
			buf.WriteString(", ")
		}
		buf.WriteString("when")
		buf.WriteString(variant.TypeName)
		buf.WriteString(" func(")
		buf.WriteString(types.TypeString(variant.Type, qualifier))
		buf.WriteString(") (")
		buf.WriteString(strings.Join(match2ReturnTypes, ", "))
		buf.WriteString(")")
	}
	buf.WriteString(") (")
	buf.WriteString(strings.Join(match2ReturnTypes, ", "))
	buf.WriteString(") {\n\tswitch x := v.(type) {\n")
	for _, variant := range generatedType.Sum.Variants {
		typeString := types.TypeString(variant.Type, qualifier)
		buf.WriteString("\tcase *")
		buf.WriteString(typeString)
		buf.WriteString(":\n\t\tif x != nil {\n\t\t\treturn when")
		buf.WriteString(variant.TypeName)
		buf.WriteString("(*x)\n\t\t}\n\t\tvar zero ")
		buf.WriteString(typeString)
		buf.WriteString("\n\t\treturn when")
		buf.WriteString(variant.TypeName)
		buf.WriteString("(zero)\n")
	}
	buf.WriteString("\tdefault:\n\t\tpanic(fmt.Sprintf(\"unreachable generated match for %T\", v))\n\t}\n}\n\n")

	// 3. Cases Struct & Match<Sum>Cases
	buf.WriteString("type ")
	buf.WriteString(generatedType.Name)
	buf.WriteString("Cases")
	writeFunctionTypeParameters(buf, generatedType.TypeParameters, matchReturnType)
	buf.WriteString(" struct {\n")
	for _, variant := range generatedType.Sum.Variants {
		buf.WriteString("\t")
		buf.WriteString(variant.TypeName)
		buf.WriteString(" func(")
		buf.WriteString(types.TypeString(variant.Type, qualifier))
		buf.WriteString(") ")
		buf.WriteString(matchReturnType[0])
		buf.WriteString("\n")
	}
	buf.WriteString("\tDefault func(")
	writeGeneratedTypeName(buf, generatedType, false)
	buf.WriteString(") ")
	buf.WriteString(matchReturnType[0])
	buf.WriteString("\n}\n\n")

	buf.WriteString("func Match")
	buf.WriteString(generatedType.Name)
	buf.WriteString("Cases")
	writeFunctionTypeParameters(buf, generatedType.TypeParameters, matchReturnType)
	buf.WriteString("(v ")
	writeGeneratedTypeName(buf, generatedType, false)
	buf.WriteString(", cases ")
	buf.WriteString(generatedType.Name)
	buf.WriteString("Cases")
	if len(generatedType.TypeParameters) > 0 || len(matchReturnType) > 0 {
		buf.WriteString("[")
		typeParamNames := renderTypeParameterNames(generatedType.TypeParameters)
		allParams := append(typeParamNames, matchReturnType...)
		buf.WriteString(strings.Join(allParams, ", "))
		buf.WriteString("]")
	}
	buf.WriteString(") ")
	buf.WriteString(matchReturnType[0])
	buf.WriteString(" {\n\tswitch x := v.(type) {\n")
	for _, variant := range generatedType.Sum.Variants {
		typeString := types.TypeString(variant.Type, qualifier)
		buf.WriteString("\tcase *")
		buf.WriteString(typeString)
		buf.WriteString(":\n\t\tif cases.")
		buf.WriteString(variant.TypeName)
		buf.WriteString(" != nil {\n\t\t\tif x != nil {\n\t\t\t\treturn cases.")
		buf.WriteString(variant.TypeName)
		buf.WriteString("(*x)\n\t\t\t}\n\t\t\tvar zero ")
		buf.WriteString(typeString)
		buf.WriteString("\n\t\t\treturn cases.")
		buf.WriteString(variant.TypeName)
		buf.WriteString("(zero)\n\t\t}\n")
	}
	buf.WriteString("\t}\n\tif cases.Default != nil {\n\t\treturn cases.Default(v)\n\t}\n\tpanic(fmt.Sprintf(\"unhandled %T variant for ")
	buf.WriteString(generatedType.Name)
	buf.WriteString("\", v))\n}\n\n")

	// 4. Cases2 Struct & Match<Sum>Cases2
	buf.WriteString("type ")
	buf.WriteString(generatedType.Name)
	buf.WriteString("Cases2")
	writeFunctionTypeParameters(buf, generatedType.TypeParameters, match2ReturnTypes)
	buf.WriteString(" struct {\n")
	for _, variant := range generatedType.Sum.Variants {
		buf.WriteString("\t")
		buf.WriteString(variant.TypeName)
		buf.WriteString(" func(")
		buf.WriteString(types.TypeString(variant.Type, qualifier))
		buf.WriteString(") (")
		buf.WriteString(strings.Join(match2ReturnTypes, ", "))
		buf.WriteString(")\n")
	}
	buf.WriteString("\tDefault func(")
	writeGeneratedTypeName(buf, generatedType, false)
	buf.WriteString(") (")
	buf.WriteString(strings.Join(match2ReturnTypes, ", "))
	buf.WriteString(")\n}\n\n")

	buf.WriteString("func Match")
	buf.WriteString(generatedType.Name)
	buf.WriteString("Cases2")
	writeFunctionTypeParameters(buf, generatedType.TypeParameters, match2ReturnTypes)
	buf.WriteString("(v ")
	writeGeneratedTypeName(buf, generatedType, false)
	buf.WriteString(", cases ")
	buf.WriteString(generatedType.Name)
	buf.WriteString("Cases2")
	if len(generatedType.TypeParameters) > 0 || len(match2ReturnTypes) > 0 {
		buf.WriteString("[")
		typeParamNames := renderTypeParameterNames(generatedType.TypeParameters)
		allParams := append(typeParamNames, match2ReturnTypes...)
		buf.WriteString(strings.Join(allParams, ", "))
		buf.WriteString("]")
	}
	buf.WriteString(") (")
	buf.WriteString(strings.Join(match2ReturnTypes, ", "))
	buf.WriteString(") {\n\tswitch x := v.(type) {\n")
	for _, variant := range generatedType.Sum.Variants {
		typeString := types.TypeString(variant.Type, qualifier)
		buf.WriteString("\tcase *")
		buf.WriteString(typeString)
		buf.WriteString(":\n\t\tif cases.")
		buf.WriteString(variant.TypeName)
		buf.WriteString(" != nil {\n\t\t\tif x != nil {\n\t\t\t\treturn cases.")
		buf.WriteString(variant.TypeName)
		buf.WriteString("(*x)\n\t\t\t}\n\t\t\tvar zero ")
		buf.WriteString(typeString)
		buf.WriteString("\n\t\t\treturn cases.")
		buf.WriteString(variant.TypeName)
		buf.WriteString("(zero)\n\t\t}\n")
	}
	buf.WriteString("\t}\n\tif cases.Default != nil {\n\t\treturn cases.Default(v)\n\t}\n\tpanic(fmt.Sprintf(\"unhandled %T variant for ")
	buf.WriteString(generatedType.Name)
	buf.WriteString("\", v))\n}\n\n")

	// 5. Visit<Sum>
	buf.WriteString("func Visit")
	buf.WriteString(generatedType.Name)
	writeFunctionTypeParameters(buf, generatedType.TypeParameters, nil)
	buf.WriteString("(v ")
	writeGeneratedTypeName(buf, generatedType, false)
	buf.WriteString(", ")
	for i, variant := range generatedType.Sum.Variants {
		if i > 0 {
			buf.WriteString(", ")
		}
		buf.WriteString("when")
		buf.WriteString(variant.TypeName)
		buf.WriteString(" func(")
		buf.WriteString(types.TypeString(variant.Type, qualifier))
		buf.WriteString(")")
	}
	buf.WriteString(") {\n\tswitch x := v.(type) {\n")
	for _, variant := range generatedType.Sum.Variants {
		typeString := types.TypeString(variant.Type, qualifier)
		buf.WriteString("\tcase *")
		buf.WriteString(typeString)
		buf.WriteString(":\n\t\tif x != nil {\n\t\t\twhen")
		buf.WriteString(variant.TypeName)
		buf.WriteString("(*x)\n\t\t} else {\n\t\t\tvar zero ")
		buf.WriteString(typeString)
		buf.WriteString("\n\t\t\twhen")
		buf.WriteString(variant.TypeName)
		buf.WriteString("(zero)\n\t\t}\n")
	}
	buf.WriteString("\tdefault:\n\t\tpanic(fmt.Sprintf(\"unreachable generated visit for %T\", v))\n\t}\n}\n")
}

func renderSumDiscriminatorMarshalUnmarshalFunctions(buf *bytes.Buffer, generatedType model.GeneratedType, qualifier types.Qualifier) {
	discriminatorKey := generatedType.Sum.Discriminator

	// 1. Marshal<Name>
	buf.WriteString("func Marshal")
	buf.WriteString(generatedType.Name)
	writeFunctionTypeParameters(buf, generatedType.TypeParameters, nil)
	buf.WriteString("(v ")
	writeGeneratedTypeName(buf, generatedType, false)
	buf.WriteString(") ([]byte, error) {\n")
	buf.WriteString("\tif v == nil {\n\t\treturn []byte(\"null\"), nil\n\t}\n")
	buf.WriteString("\tswitch x := v.(type) {\n")
	for _, variant := range generatedType.Sum.Variants {
		typeString := types.TypeString(variant.Type, qualifier)
		buf.WriteString("\tcase *")
		buf.WriteString(typeString)
		buf.WriteString(":\n\t\tif x == nil {\n\t\t\treturn []byte(\"null\"), nil\n\t\t}\n\t\treturn marshalWith")
		buf.WriteString(generatedType.Name)
		buf.WriteString("Discriminator(")
		buf.WriteString(strconv.Quote(discriminatorKey))
		buf.WriteString(", ")
		buf.WriteString(strconv.Quote(variant.TypeName))
		buf.WriteString(", *x)\n")
	}
	buf.WriteString("\tdefault:\n\t\treturn nil, fmt.Errorf(\"unknown ")
	buf.WriteString(generatedType.Name)
	buf.WriteString(" variant %T\", v)\n\t}\n}\n\n")

	// 2. Helper marshalWith<Name>Discriminator
	buf.WriteString("func marshalWith")
	buf.WriteString(generatedType.Name)
	buf.WriteString("Discriminator(key, typeName string, v any) ([]byte, error) {\n")
	buf.WriteString("\tdata, err := json.Marshal(v)\n")
	buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	buf.WriteString("\tvar obj map[string]json.RawMessage\n")
	buf.WriteString("\tif err := json.Unmarshal(data, &obj); err != nil {\n\t\treturn nil, err\n\t}\n")
	buf.WriteString("\tif obj == nil {\n\t\tobj = make(map[string]json.RawMessage)\n\t}\n")
	buf.WriteString("\ttypeJSON, err := json.Marshal(typeName)\n")
	buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	buf.WriteString("\tobj[key] = typeJSON\n")
	buf.WriteString("\treturn json.Marshal(obj)\n}\n\n")

	// 3. Unmarshal<Name>
	buf.WriteString("func Unmarshal")
	buf.WriteString(generatedType.Name)
	writeFunctionTypeParameters(buf, generatedType.TypeParameters, nil)
	buf.WriteString("(data []byte) (")
	writeGeneratedTypeName(buf, generatedType, false)
	buf.WriteString(", error) {\n")
	buf.WriteString("\tvar header struct {\n")
	buf.WriteString("\t\tType string `json:\"")
	buf.WriteString(discriminatorKey)
	buf.WriteString("\"`\n\t}\n")
	buf.WriteString("\tif err := json.Unmarshal(data, &header); err != nil {\n\t\treturn nil, err\n\t}\n")
	buf.WriteString("\tswitch header.Type {\n")
	for _, variant := range generatedType.Sum.Variants {
		typeString := types.TypeString(variant.Type, qualifier)
		buf.WriteString("\tcase ")
		buf.WriteString(strconv.Quote(variant.TypeName))
		buf.WriteString(":\n\t\tvar target ")
		buf.WriteString(typeString)
		buf.WriteString("\n\t\tif err := json.Unmarshal(data, &target); err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
		buf.WriteString("\t\treturn &target, nil\n")
	}
	buf.WriteString("\tdefault:\n\t\treturn nil, fmt.Errorf(\"unknown discriminator %q for ")
	buf.WriteString(generatedType.Name)
	buf.WriteString("\", header.Type)\n\t}\n}\n")
}

func renderSumUnmarshalFunction(buf *bytes.Buffer, generatedType model.GeneratedType, qualifier types.Qualifier) {
	buf.WriteString("func Unmarshal")
	buf.WriteString(generatedType.Name)
	writeFunctionTypeParameters(buf, generatedType.TypeParameters, nil)
	buf.WriteString("(data []byte) (")
	writeGeneratedTypeName(buf, generatedType, false)
	buf.WriteString(", error) {\n\tvar result ")
	writeGeneratedTypeName(buf, generatedType, false)
	buf.WriteString("\n\tmatches := 0\n")

	for _, variant := range generatedType.Sum.Variants {
		typeString := types.TypeString(variant.Type, qualifier)
		buf.WriteString("\t{\n\t\tvar candidate ")
		buf.WriteString(typeString)
		buf.WriteString("\n\t\tdecoder := json.NewDecoder(bytes.NewReader(data))\n\t\tdecoder.DisallowUnknownFields()\n")
		buf.WriteString("\t\tif err := decoder.Decode(&candidate); err == nil {\n")
		buf.WriteString("\t\t\tvar trailing struct{}\n")
		buf.WriteString("\t\t\tif err := decoder.Decode(&trailing); err == io.EOF {\n")
		buf.WriteString("\t\t\t\tmatches++\n\t\t\t\tresult = &candidate\n\t\t\t}\n\t\t}\n\t}\n")
	}

	buf.WriteString("\tif matches == 1 {\n\t\treturn result, nil\n\t}\n")
	buf.WriteString("\tif matches == 0 {\n\t\treturn nil, fmt.Errorf(\"no variants of ")
	buf.WriteString(generatedType.Name)
	buf.WriteString(" matched JSON\")\n\t}\n")
	buf.WriteString("\treturn nil, fmt.Errorf(\"multiple variants of ")
	buf.WriteString(generatedType.Name)
	buf.WriteString(" matched JSON\")\n}\n")
}

func selectorPath(root string, path []string) string {
	if len(path) == 0 {
		return root
	}
	return root + "." + strings.Join(path, ".")
}

func renderConstructor(buf *bytes.Buffer, generatedType model.GeneratedType, qualifier types.Qualifier) {
	buf.WriteString("func New")
	writeGeneratedTypeName(buf, generatedType, true)
	buf.WriteString("(")
	for i, input := range generatedType.Inputs {
		if i > 0 {
			buf.WriteString(", ")
		}
		buf.WriteString(input.ParameterName)
		buf.WriteString(" ")
		buf.WriteString(types.TypeString(input.Type, qualifier))
	}
	buf.WriteString(") ")
	writeGeneratedTypeName(buf, generatedType, false)
	buf.WriteString(" {\n\treturn ")
	writeGeneratedTypeName(buf, generatedType, false)
	buf.WriteString("{\n")

	seen := make(map[string]struct{})
	for _, input := range generatedType.Inputs {
		for _, fieldName := range input.FieldNames {
			if _, ok := seen[fieldName]; ok {
				// Duplicate fields have already been verified by ComposeFields to be
				// structurally identical anonymous fields. Thus, initializing from
				// the first encountered input is safe and correct.
				continue
			}
			seen[fieldName] = struct{}{}
			buf.WriteString("\t\t")
			buf.WriteString(fieldName)
			buf.WriteString(": ")
			buf.WriteString(input.ParameterName)
			buf.WriteString(".")
			buf.WriteString(fieldName)
			buf.WriteString(",\n")
		}
	}

	buf.WriteString("\t}\n}\n")
}

func renderSplitMethod(buf *bytes.Buffer, generatedType model.GeneratedType, input model.GeneratedInput, qualifier types.Qualifier) {
	buf.WriteString("func (x ")
	writeGeneratedTypeName(buf, generatedType, false)
	buf.WriteString(") ")
	buf.WriteString(input.MethodName)
	buf.WriteString("() ")
	buf.WriteString(types.TypeString(input.Type, qualifier))
	buf.WriteString(" {\n\treturn ")
	buf.WriteString(types.TypeString(input.Type, qualifier))
	buf.WriteString("{\n")
	for _, fieldName := range input.FieldNames {
		buf.WriteString("\t\t")
		buf.WriteString(fieldName)
		buf.WriteString(": x.")
		buf.WriteString(fieldName)
		buf.WriteString(",\n")
	}
	buf.WriteString("\t}\n}\n")
}

func writeGeneratedTypeName(buf *bytes.Buffer, generatedType model.GeneratedType, withConstraints bool) {
	if len(generatedType.TypeParameters) == 0 {
		buf.WriteString(generatedType.Name)
		return
	}

	params := generatedType.TypeParameters
	if !withConstraints {
		params = renderTypeParameterNames(generatedType.TypeParameters)
	}

	buf.WriteString(generatedType.Name)
	buf.WriteString("[")
	for i, param := range params {
		if i > 0 {
			buf.WriteString(", ")
		}
		buf.WriteString(param)
	}
	buf.WriteString("]")
}

func writeFunctionTypeParameters(buf *bytes.Buffer, typeParameters []string, extraNames []string) {
	if len(typeParameters) == 0 && len(extraNames) == 0 {
		return
	}

	buf.WriteString("[")
	wrote := false
	for _, parameter := range typeParameters {
		if wrote {
			buf.WriteString(", ")
		}
		buf.WriteString(parameter)
		wrote = true
	}
	if len(extraNames) > 0 {
		if wrote {
			buf.WriteString(", ")
		}
		for i, name := range extraNames {
			if i > 0 {
				buf.WriteString(", ")
			}
			buf.WriteString(name)
		}
		buf.WriteString(" any")
	}
	buf.WriteString("]")
}

func renderTypeParameterNames(typeParameters []string) []string {
	names := make([]string, 0, len(typeParameters))
	for _, parameter := range typeParameters {
		fields := strings.Fields(parameter)
		if len(fields) == 0 {
			continue
		}
		names = append(names, strings.TrimSuffix(fields[0], ","))
	}
	return names
}

func uniqueTypeParameterNames(typeParameters []string, bases ...string) []string {
	used := make(map[string]struct{}, len(typeParameters)+len(bases))
	for _, name := range renderTypeParameterNames(typeParameters) {
		used[name] = struct{}{}
	}

	names := make([]string, 0, len(bases))
	for _, base := range bases {
		name := base
		if _, ok := used[name]; !ok {
			used[name] = struct{}{}
			names = append(names, name)
			continue
		}

		for i := 1; ; i++ {
			candidate := fmt.Sprintf("%s%d", base, i)
			if _, ok := used[candidate]; ok {
				continue
			}
			used[candidate] = struct{}{}
			names = append(names, candidate)
			break
		}
	}

	return names
}

func variantIndex(variants []model.GeneratedSumVariant, typeName string) int {
	for i, variant := range variants {
		if variant.TypeName == typeName {
			return i
		}
	}
	return -1
}
