package emitter

import (
	"go/token"
	"go/types"
	"strings"
	"testing"

	"github.com/walnuts1018/go-product-type/internal/model"
)

func TestRenderIncludesHeaderPackageAndTypeDefinition(t *testing.T) {
	src, err := Render("sample", []model.GeneratedType{
		{
			Name: "AB",
			Fields: []model.GeneratedField{
				{Name: "ID", Type: types.Typ[types.String]},
			},
		},
	})
	if err != nil {
		t.Fatalf("Render() error = %v", err)
	}

	for _, want := range []string{
		"// Code generated by goproducttype. DO NOT EDIT.",
		"//go:build !goproducttype_generate",
		"package sample",
		"type AB struct",
	} {
		if !strings.Contains(src, want) {
			t.Fatalf("Render() output missing %q:\n%s", want, src)
		}
	}
}

func TestRenderIncludesImportsTypeParametersAnonymousFieldsAndTags(t *testing.T) {
	timePkg := types.NewPackage("time", "time")
	timeType := types.NewNamed(
		types.NewTypeName(token.NoPos, timePkg, "Time", nil),
		types.NewStruct(nil, nil),
		nil,
	)
	depPkg := types.NewPackage("example.com/dep", "dep")
	embeddedType := types.NewNamed(
		types.NewTypeName(token.NoPos, depPkg, "Embedded", nil),
		types.NewStruct(nil, nil),
		nil,
	)
	typeParam := types.NewTypeParam(types.NewTypeName(token.NoPos, nil, "T", nil), types.Universe.Lookup("any").Type())

	src, err := Render("sample", []model.GeneratedType{
		{
			Name:           "Pair",
			TypeParameters: []string{"T comparable", "U interface{ String() string }"},
			Fields: []model.GeneratedField{
				{Name: "CreatedAt", Type: timeType, Tag: `json:"created_at"`},
				{Name: "Embedded", Type: types.NewPointer(embeddedType), Anonymous: true},
				{Name: "Value", Type: typeParam},
			},
		},
	})
	if err != nil {
		t.Fatalf("Render() error = %v", err)
	}

	for _, want := range []string{
		"import (\n\t\"example.com/dep\"\n\t\"time\"\n)",
		"type Pair[T comparable, U interface{ String() string }] struct {",
		"CreatedAt time.Time `json:\"created_at\"`",
		"*dep.Embedded",
		"Value T",
	} {
		if !strings.Contains(src, want) {
			t.Fatalf("Render() output missing %q:\n%s", want, src)
		}
	}

	createdAtIndex := strings.Index(src, "CreatedAt time.Time")
	embeddedIndex := strings.Index(src, "*dep.Embedded")
	valueIndex := strings.Index(src, "Value T")
	if !(createdAtIndex >= 0 && createdAtIndex < embeddedIndex && embeddedIndex < valueIndex) {
		t.Fatalf("Render() did not preserve field order:\n%s", src)
	}
}

func TestRenderForPackageImportsExternalTypeWithSamePackageName(t *testing.T) {
	samplePkg := types.NewPackage("example.com/other/sample", "sample")
	externalType := types.NewNamed(
		types.NewTypeName(token.NoPos, samplePkg, "External", nil),
		types.NewStruct(nil, nil),
		nil,
	)

	src, err := RenderForPackage("example.com/current/sample", "sample", []model.GeneratedType{
		{
			Name: "AB",
			Fields: []model.GeneratedField{
				{Name: "Value", Type: externalType},
			},
		},
	})
	if err != nil {
		t.Fatalf("RenderForPackage() error = %v", err)
	}

	for _, want := range []string{
		"\"example.com/other/sample\"",
		"Value sample.External",
	} {
		if !strings.Contains(src, want) {
			t.Fatalf("RenderForPackage() output missing %q:\n%s", want, src)
		}
	}
}
