package emitter

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"sort"
	"strings"

	"github.com/walnuts1018/go-product-type/internal/model"
)

func Render(pkgName string, generated []model.GeneratedType) (string, error) {
	return RenderForPackage("", pkgName, generated)
}

func RenderForPackage(pkgPath string, pkgName string, generated []model.GeneratedType) (string, error) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by goproducttype. DO NOT EDIT.\n")
	buf.WriteString("//go:build !goproducttype_generate\n\n")
	buf.WriteString("package " + pkgName + "\n\n")

	imports := collectImports(pkgPath, generated)
	if len(imports) > 0 {
		buf.WriteString("import (\n")
		for _, path := range imports {
			buf.WriteString(fmt.Sprintf("\t%q\n", path))
		}
		buf.WriteString(")\n\n")
	}

	qualifier := func(typePkg *types.Package) string {
		if typePkg == nil {
			return ""
		}
		if pkgPath != "" && typePkg.Path() == pkgPath {
			return ""
		}
		return typePkg.Name()
	}

	for i, generatedType := range generated {
		if i > 0 {
			buf.WriteString("\n")
		}

		buf.WriteString("type ")
		buf.WriteString(generatedType.Name)
		if len(generatedType.TypeParameters) > 0 {
			buf.WriteString("[")
			buf.WriteString(strings.Join(generatedType.TypeParameters, ", "))
			buf.WriteString("]")
		}
		buf.WriteString(" struct {\n")

		for _, field := range generatedType.Fields {
			buf.WriteString("\t")
			if !field.Anonymous {
				buf.WriteString(field.Name)
				buf.WriteString(" ")
			}
			buf.WriteString(types.TypeString(field.Type, qualifier))
			if field.Tag != "" {
				buf.WriteString(fmt.Sprintf(" `%s`", field.Tag))
			}
			buf.WriteString("\n")
		}

		buf.WriteString("}\n")
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return "", err
	}

	return string(formatted), nil
}

func collectImports(pkgName string, generated []model.GeneratedType) []string {
	seen := make(map[string]struct{})

	for _, generatedType := range generated {
		for _, field := range generatedType.Fields {
			collectTypeImports(pkgName, field.Type, seen)
		}
	}

	imports := make([]string, 0, len(seen))
	for path := range seen {
		imports = append(imports, path)
	}
	sort.Strings(imports)
	return imports
}

func collectTypeImports(pkgPath string, typ types.Type, seen map[string]struct{}) {
	if typ == nil {
		return
	}

	switch t := typ.(type) {
	case *types.Basic:
		return
	case *types.Pointer:
		collectTypeImports(pkgPath, t.Elem(), seen)
	case *types.Slice:
		collectTypeImports(pkgPath, t.Elem(), seen)
	case *types.Array:
		collectTypeImports(pkgPath, t.Elem(), seen)
	case *types.Map:
		collectTypeImports(pkgPath, t.Key(), seen)
		collectTypeImports(pkgPath, t.Elem(), seen)
	case *types.Chan:
		collectTypeImports(pkgPath, t.Elem(), seen)
	case *types.Signature:
		if recv := t.Recv(); recv != nil {
			collectTypeImports(pkgPath, recv.Type(), seen)
		}
		collectTupleImports(pkgPath, t.Params(), seen)
		collectTupleImports(pkgPath, t.Results(), seen)
	case *types.Struct:
		for i := 0; i < t.NumFields(); i++ {
			collectTypeImports(pkgPath, t.Field(i).Type(), seen)
		}
	case *types.Interface:
		for i := 0; i < t.NumEmbeddeds(); i++ {
			collectTypeImports(pkgPath, t.EmbeddedType(i), seen)
		}
	case *types.Named:
		if obj := t.Obj(); obj != nil && obj.Pkg() != nil && obj.Pkg().Path() != pkgPath {
			seen[obj.Pkg().Path()] = struct{}{}
		}
		if args := t.TypeArgs(); args != nil {
			for i := 0; i < args.Len(); i++ {
				collectTypeImports(pkgPath, args.At(i), seen)
			}
		}
	case *types.Alias:
		if obj := t.Obj(); obj != nil && obj.Pkg() != nil && obj.Pkg().Path() != pkgPath {
			seen[obj.Pkg().Path()] = struct{}{}
		}
		collectTypeImports(pkgPath, types.Unalias(t), seen)
	case *types.TypeParam:
		return
	case *types.Union:
		for i := 0; i < t.Len(); i++ {
			collectTypeImports(pkgPath, t.Term(i).Type(), seen)
		}
	case *types.Tuple:
		collectTupleImports(pkgPath, t, seen)
	}
}

func collectTupleImports(pkgPath string, tuple *types.Tuple, seen map[string]struct{}) {
	if tuple == nil {
		return
	}
	for i := 0; i < tuple.Len(); i++ {
		collectTypeImports(pkgPath, tuple.At(i).Type(), seen)
	}
}
