// Code generated by go-adtgen. DO NOT EDIT.
//go:build !adtgen_generate

package passthrough

import "fmt"

const InlinePrefix = "inline"

type Inline struct {
	Label string
}

var DefaultInline = Inline{Label: InlinePrefix}

func FormatInline(x Inline) string {
	return fmt.Sprintf("%s:%s", InlinePrefix, x.Label)
}

type Combined struct {
	Label string
	Count int
}

func NewCombined(inline Inline, shared Shared) Combined {
	return Combined{
		Label: inline.Label,
		Count: shared.Count,
	}
}

func (x Combined) ToInline() Inline {
	return Inline{
		Label: x.Label,
	}
}

func (x Combined) ToShared() Shared {
	return Shared{
		Count: x.Count,
	}
}
